<!DOCTYPE html>
<html lang="en">

<head>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MBRPLPL');</script>
<!-- End Google Tag Manager -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-205315179-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-205315179-1');
</script>

<!-- Meta SEO Tags -->
<meta content="" name="generator">
<meta content="The Roots Restaurant serves the most authentic Ugandan Cuisine in a serene uptown environment and prepared with care to avoid any unnatural additives, ensuring your great health. Here you will find dishes from most parts of Uganda including the signature Luwombo from Buganda, the famous BOO from Acholi, and Filinda as you have never experienced it before, to mention but a few!" name="description">
<meta content=">Best local food restaurant in uptown Kampla, Luwombo, Matooke, Kalo, Garden, Roast Chicken, Roast Goat, Ugandan food, Eat out, Katogo, Healthy food, Boiled food, Fresh fruit juice, Smoked whole fish, Roots Restaurant, Kampala, Uganda, Nakasero, Food, Localfood, The Roots Restaurant, Good food, The Roots Restaurant, Nice Food,uptown,tasty" name="keywords">
<!-- Meta SEO Tags -->

  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link href="static/images/favicon/favicon.png" rel="icon">
  <title>The Roots Restaurant - Authentic Ugandan Cuisine</title>
  <link rel="stylesheet" href="static/css/libraries.css"/>
  <link rel="stylesheet" href="static/css/style.css" />
</head>

<body>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MBRPLPL" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Restaurant",
  "name" : "The Roots Restaurant",
  "image" : "https://therootsrestaurant.ug/static/images/logo/logo-dark.png",
  "telephone" : "0772377375",
  "email" : "roots@therootsresturant.ug",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "Plot 4, Kafu Road",
    "addressLocality" : "Kampala",
    "addressRegion" : "Kampala",
    "addressCountry" : "Uganda"
  },
  "menu" : "https://therootsrestaurant.ug/menu",
  "servesCuisine" : "Authentic Ugandan Cuisine",
  "url" : "https://therootsrestaurant.ug/"
}
</script>

  <div class="wrapper">


<!-- Include Header -->
<?php include_once( "header.php" ); ?>


    <!-- ========================
    Slider
    ============================== -->
    <section id="slider" class="slider slider-layout1">
      <div class="carousel owl-carousel carousel-arrows carousel-dots carousel-dots-light" data-slide="1"
        data-slide-md="1" data-slide-sm="1" data-autoplay="true" data-nav="true" data-dots="true" data-space="0"
        data-loop="true" data-speed="3000" data-transition="fade" data-animate-out="fadeOut" data-animate-in="fadeIn">


        <div class="slide-item align-v-h text-center bg-overlay">
          <div class="bg-img"><img src="static/images/backgrounds/main-3.jpg" alt="slide img"></div>
          <div class="spikes"></div><!-- divider-shape -->
          <div class="container">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="slide__content">
                  <h2 class="slide__title">An Authentic <br> Ugandan Cuisine</h2>
                  <p class="slide__desc">Offering The Best Tasting Experience!</p>
                  <a href="menu" class="btn btn__primary btn__hover2 ">View Menu</a>
                  <a href="reservation" class="btn btn__white btn__bordered mx-2">Make a Reservation</a>
                </div>
              </div>
            </div>
          </div>
        </div>


        <div class="slide-item align-v-h text-center bg-overlay">
          <div class="bg-img"><img src="static/images/backgrounds/20.jpg" alt="slide img"></div>
          <div class="spikes"></div>
          <div class="container">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="slide__content">
                  <h2 class="slide__title">Serene Outdoor<br> Garden Experience</h2>
                  <p class="slide__desc">Calming and Peaceful atmosphere</p>
                  <a href="gallery" class="btn btn__primary mx-2">Gallery</a>
                  <a href="services" class="btn btn__white btn__bordered mx-2">Our Services</a>
                </div>
              </div>
            </div>
          </div>
        </div>


      </div>
    </section>



    <!-- =========================== 
      Featured Section
    ============================= -->
    <section class="features" style="background-image: url('static/images/backgrounds/bg-1.jpg');">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-8 offset-lg-2">
            <div class="heading heading-layout1 text-center mb-50">
              <span class="heading__subtitle">Welcome To The Roots Restaurant</span>
              <h2 class="heading__title">An Authentic Ugandan Cuisine</h2>
              <div class="heading__icon">
                <img src="static/images/shapes/shape2.png" alt="heading img">
              </div>
            </div>
          </div>
        </div>
        <div class="row">



          <!-- feature item #1 -->
          <div class="col-sm-12 col-md-4 col-lg-4">
            <a href="https://food.jumia.ug/restaurant/k2vr/the-roots-restaurant" target="_blank">
              <div class="feature-item">
                <div class="feature__img">
                  <img src="static/images/features/6.jpg" alt="feature img">
                </div>
                <div class="feature__content">
                  <h4 class="feature__title"></h4>
                </div>
              </div>
            </a>
          </div>


          <!-- feature item #2 -->
          <div class="col-sm-12 col-md-4 col-lg-4">
            <a href="menu">
              <div class="feature-item">
                <div class="feature__img">
                  <img src="static/images/features/5.jpg" alt="feature img">
                </div>
                <div class="feature__content">
                  <h4 class="feature__title"></h4>
                </div>
              </div>
            </a>
          </div>

        <!-- feature item #3 -->
          <div class="col-sm-12 col-md-4 col-lg-4">
            <a href="menu">
              <div class="feature-item">
                <div class="feature__img">
                  <img src="static/images/features/4.jpg" alt="feature img">
                </div>
                <div class="feature__content">
                  <h4 class="feature__title"></h4>
                </div>
              </div>
            </a>
          </div>



        </div>


        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3 text-center">
            <img src="static/images/logo/footer-logo.png" alt=""><br><br>
            <p>The serene, out and indoor experience is an unforgettable one because no other Restaurant in Kampala offers such environment.
               Our staff is courteous and helpful at every turn.
                Come enjoy the best Ugandan cuisine in the best environment!</p>
            <a class="btn btn__secondary btn__link" href="about">Discover More About Us</a>
          </div>
        </div>


      </div>
    </section>

    <!-- ========================
       Taste . Experience . Health 
    =========================== -->
    <section class="cta-layout2 text-center bg-overlay bg-parallax">
      <div class="bg-img"><img src="static/images/backgrounds/22.jpg" alt="background"></div>
      <div class="divider-shape"></div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
            <span class="cta__subtitle">Taste . Experience . Health</span>
            <h2 class="heading__title color-white"></h2>
            <p class="cta__desc">At the Roots Restaurant, we ensure that your meal is as pure as it was intended <br> 
            for your body! No additives, no oil and cooked in the most natural way possible.</p>
              <a href="menu" class="btn btn__white mx-1">View The Roots Menu</a>
            <a href="reservation" class="btn btn__white mx-1">Book A Table</a>
          </div>
        </div>
      </div>
    </section>



    <!-- ========================
        ROOTS MENU
    =========================== -->
    <section class="menu-layout1">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
            <div class="heading heading-layout1 text-center mb-50">
              <span class="heading__subtitle">Our Signature Dishes</span>
              <h2 class="heading__title "></h2>
              <div class="heading__icon">
                <img src="static/images/shapes/shape2.png" alt="heading img">
              </div>
              <p class="heading__desc">Our Menu has been carefully and thoughtfully put together to give you a taste of East Africa and a taste of Uganda.</p>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-4">
            <img src="static/images/menu/1.jpg" alt="menu" class="mb-40">
            <div class="menu-item">
              <h4 class="menu__item-title">GOAT LUWOMBO</h4>
              <span class="menu__item-price">30,000 Ugx</span>
              <p class="menu__item-desc">Steamed in banana leaf with onion, tomato and salt </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">GOAT STEW</h4>
              <span class="menu__item-price">30,000 Ugx</span>
              <p class="menu__item-desc">Delicately stewed with onion, tomato and salt </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">ROAST GOAT</h4>
              <span class="menu__item-price">25,000 Ugx</span>
              <p class="menu__item-desc">Tender, carefully char-grilled goat's meat, served with a roast Tooke and Kachumbari </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">CHICKEN LUWOMBO</h4>
              <span class="menu__item-price">29,000 Ugx</span>
              <p class="menu__item-desc">Local free-range chicken slightly char-grilled and steamed in banana leaf with onion, tomato & salt </p>
            </div>
          </div>
          <div class="col-sm-12 col-md-12 col-lg-4">
            <img src="static/images/menu/2.jpg" alt="menu" class="mb-40">
            <div class="menu-item">
              <h4 class="menu__item-title">CHICKEN ROAST</h4>
              <span class="menu__item-price">25,000 Ugx </span>
              <p class="menu__item-desc">Charcoal grilled and served with kachumbari (Tomato & Onion Salad) and a roast matooke </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">BEEF LUWOMBO</h4>
              <span class="menu__item-price">28,000 Ugx</span>
              <p class="menu__item-desc">Slightly char-grilled, then steamed to perfection in a banana leaf with onion & Tomato </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">BEEF IN G.NUT LUWOMBO</h4>
              <span class="menu__item-price">29,000 Ugx</span>
              <p class="menu__item-desc">Freshly char-grilled beef, then mixed with ground(pea)nut paste and steamed in banana leaf </p>
            </div>
            
          </div>


          <div class="col-sm-12 col-md-12 col-lg-4">
            <img src="static/images/menu/3.jpg" alt="menu" class="mb-40">
            <div class="menu-item">
              <h4 class="menu__item-title">PASTED MEAT</h4>
              <span class="menu__item-price">27,000 Ugx</span>
              <p class="menu__item-desc">Smoke dried beef mixed with ground nut & sesame seed paste </p>
            </div>
            <div class="menu-item">
              <h4 class="menu__item-title">CHICKEN STEW</h4>
              <span class="menu__item-price">28,000 Ugx</span>
              <p class="menu__item-desc">Local free-range chicken stewed to perfection with tomato & onion </p>
            </div>
          </div>
        </div>
      </div>
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12 text-center">
            <a href="menu" class="btn btn__link btn__secondary">Explore Full Menu</a>
          </div>
        </div>
      </div>
    </section>


    <!-- ==========================
        FEATURES
    =========================== -->
    <section class="fancybox-layout1 text-center pb-40">
      <div class="container">
        <div class="row">

          <!-- fancybox item #1 -->
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="fancybox-item">
              <div class="fancybox__icon">
                <img src="static/images/icons/1.png" alt="icon">
              </div>
              <div class="fancybox__content">
                <h4 class="fancybox__title">Daily Fresh Menus</h4>
                <p class="fancybox__desc">Our Menu has been carefully and thoughtfully put together to give you a taste of East Africa and a taste of Uganda.</p>
              </div>
            </div>
          </div>

          <!-- fancybox item #2 -->
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="fancybox-item">
              <div class="fancybox__icon">
                <img src="static/images/icons/2.png" alt="icon">
              </div>
              <div class="fancybox__content">
                <h4 class="fancybox__title">Fresh Ingredients</h4>
                <p class="fancybox__desc">Here you will find dishes from most parts of Uganda including the signature Luwombo from Buganda, the famous BOO from Acholi, and Filinda as you have never experienced it before,</p>
              </div>
            </div>
          </div>

          <!-- fancybox item #3 -->
          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="fancybox-item">
              <div class="fancybox__icon">
                <img src="static/images/icons/3.png" alt="icon">
              </div>
              <div class="fancybox__content">
                <h4 class="fancybox__title">Tasty Meals</h4>
                <p class="fancybox__desc">Our meals are prepared with care to avoid any unnatural additives, ensuring your great health.</p>
              </div>
            </div>
          </div>


        </div>
      </div>
    </section>

    

      <!-- ========================= 
      Customer Reviews
    =========================  -->
    <section class="testimonials testimonials-layout1 bg-overlay">
      <div class="bg-img"><img src="static/images/backgrounds/3.jpg" alt="background"></div>
      <div class="divider-shape"></div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6">
            <div class="heading heading-layout1 text-left mb-50">
              <span class="heading__subtitle">What They Say</span>
              <h2 class="heading__title color-white">Our Customer Reviews</h2>
              
              <div class="heading__icon">
                <img src="static/images/shapes/shape2.png" alt="heading img">
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="col-sm-6 col-md-6 col-lg-3">
                <center><a href="https://www.tripadvisor.com/Restaurant_Review-g293841-d10288159-Reviews-The_Roots_Restaurant-Kampala_Central_Region.html" target="_blank"><img src="static/images/icons/ta.png" alt="" class="ta-home"></a></center>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="col-sm-6 col-md-6 col-lg-3">
                <a href="https://www.google.com/search?q=the+roots+restauranttt&rlz=1C5CHFA_enUG1015UG1015&oq=the+roots+restauranttt&aqs=chrome..69i57l2j69i59j69i60l5.4485j0j1&sourceid=chrome&ie=UTF-8#" target="_blank"><img src="static/images/icons/gg.png" alt="" style="min-width: 250px;"></a>
            </div>
          </div>


        </div>


        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="carousel owl-carousel carousel-dots carousel-dots-light" data-slide="3" data-slide-md="2"
              data-slide-sm="1" data-autoplay="true" data-nav="false" data-dots="true" data-space="30" data-loop="true"
              data-speed="800">


              
              <!-- Testimonial Item #1 -->
              <div class="testimonial-item">
                <div class="testimonial__content">
                  <div class="testimonial__rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                  <h6>Superb food and great location</h6>
                  <p class="testimonial__desc">“If you want high quality, organic local food served by attentive staff 
                    in a charming garden setting in the middle of Kampala then this is the best option in the city. 
                    And I have to say that their Covid-era food deliveries are excellent too!”</p>
                </div>
                <div class="testimonial__meta">
                  <div class="testimonial__thumb">
                    <img src="https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/e9/ef/default-avatar-2020-66.jpg" alt="author thumb">
                  </div>
                  <h5 class="testimonial__meta-title">Jonathan BP</h5>
                  <p class="testimonial__meta-desc"></p>
                </div>
              </div>


              <!-- Testimonial Item #2 -->
              <div class="testimonial-item">
                <div class="testimonial__content">
                  <div class="testimonial__rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                  <h6>The heart of Uganda food..</h6>
                  <p class="testimonial__desc">“Been to this stunning place many times over the last years. Tonight I
                    have to say, it was good as it ever was. Superb food, exceedingly good staff.”</p>
                </div>
                <div class="testimonial__meta">
                  <div class="testimonial__thumb">
                    <img src="https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/f1/06/default-avatar-2020-18.jpg" alt="author thumb">
                  </div>
                  <h5 class="testimonial__meta-title">Ropa</h5>
                </div>
              </div>

              <!-- Testimonial Item #3 -->
              <div class="testimonial-item">
                <div class="testimonial__content">
                  <div class="testimonial__rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                  <h6>Wonderful Reastaurant</h6>
                  <p class="testimonial__desc">“I had an amazing experience with family at the roots restaurant.
                    Great ambience Not only do they serve healthy local food but its very tasty as well. 
                    Prices are competitive. Will definetly be coming back soon.”</p>
                </div>
                <div class="testimonial__meta">
                  <div class="testimonial__thumb">
                    <img src="https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/eb/a3/default-avatar-2020-38.jpg" alt="author thumb">
                  </div>
                  <h5 class="testimonial__meta-title">Lucy Shantel</h5>
                </div>
              </div>




            </div>
          </div>
        </div>
      </div>
    </section>



    <!-- =====================
       Serene Uptown Environment
    ======================== -->
    <section class="banner banner-layout1">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="banner__img" data-aos="fade-right">
              <img src="static/images/banners/banner-1.jpg" alt="banner" class="img-fluid">
            </div>
          </div>
          <div class="col-6 col-sm-6 col-md-3 col-lg-3">
            <div class="banner__img mt-30" data-aos="fade-right" data-aos-delay=".5s">
              <img src="static/images/banners/banner-2.jpg" alt="banner" class="img-fluid">
            </div>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="banner__text text-right mt-30" data-aos="fade-left">
              <div class="heading heading-layout1 mb-30">
                <span class="heading__subtitle">Serene Outdoor</span>
                <h2 class="heading__title">Garden Environment!</h2>
                <div class="heading__icon">
                  <img src="static/images/shapes/shape2.png" alt="heading img">
                </div>
                <p class="heading__desc">Our naturally maintained gardens with trees, plants, flowers, birds, and crickets are sure to 
                  give you that calming and peaceful atmosphere that is hard to come by in Kampala's hustle and bustle!
                   Worry not about parking because we have ensured that all the parking space you need is provided!</p>
              </div>
              <a href="reservation" class="btn btn__secondary btn__link">Make a reservation</a>
              <a href="gallery" class="btn btn__primary" >View Gallery</a>
            </div>
          </div>
        </div>
      </div>
    </section><!-- /.Banner layout1 -->

    <!-- ========================
      Reservation
    =========================== -->
    <section class="reservation-layout2 bg-overlay bg-parallax">
      <div class="bg-img"><img src="static/images/backgrounds/8.jpg" alt="background"></div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="reservation-container">
              <div class="reservation__banner" data-aos="fade-right">
                  <img class="reservation__banner-img" src="static/images/backgrounds/pattern/3.jpg" alt="background">
                  <div class="reservation__banner-inner">
                    <span class="reservation__banner-inner-subtitle">Check Availability</span>
                    <h5 class="reservation__banner-inner-title">Opening Times</h5>
                    <ul class="list-unstyled">
                      <li><span>Mon - Sat</span><span>07:00 am – 10:00pm</span></li>
                      <li><span>Sun</span><span>09:00 am - 07:00pm</span></li>
                    </ul>
                    <div class="reservation__banner-contact">
                      <span class="reservation__banner-contact-label">Call Us Now</span>
                      <a class="reservation__banner-contact-phone" href="tel:0772494624">0772494624</a>
                    </div>
                  </div>
                </div>

            <!-- Start Reservation Form -->
            <form class="reservation__form" action="system/reserve-index.php" method="POST" data-aos="fade-left" id="resform">
                <div class="row">
                  <div class="col-sm-12 col-md-12 col-lg-12">
                    <span class="heading__subtitle">Reserve your table</span>
                    <p>Reserve for your meal or upcoming event</p>
                    <!-- Display Alert Messages -->
                    <?php 
                    if(isset($_GET['status'])){
                      $status = $_GET['status'];
                      if($status == "success"){
                        echo '<div class="alert alert-success" role="alert">Your reservation has been sent successfully, we shall be in touch shortly!</div>';
                      }elseif($status == "error"){
                        echo '<div class="alert alert-danger" role="alert">Failed to make reservation, Please try again. </div>';
                      }
                    }
                    ?>
                    <!-- Display Alert Messages -->
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name" required>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <input name="tel" type="text" class="form-control" placeholder="Phone Number" required>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="form-group">
                      <input name="email" type="text" class="form-control" placeholder="Email" required>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="form-group">
                      <input name="guests_no" type="number" class="form-control" placeholder="Number of Guests" required>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="form-group">
                      <label>Time</label>
                      <input name="time" type="time" class="form-control" placeholder="" required>
                    </div>
                  </div>

                  <div class="col-sm-6">
                    <div class="form-group">
                      <label>Date</label>
                      <input name="date" type="date" class="form-control" placeholder="" required>
                    </div>
                  </div>

                  <div class="col-sm-12">
                    <div class="form-group">
                      <h6>Select Occasion</h6>
                      <select name="occasion" class="form-control" required>
                        <option value="Breakfast">Breakfast</option>
                        <option value="Lunch">Lunch</option>
                        <option value="Dinner">Dinner</option>
                        <option value="Meeting">Meeting</option>
                        <option value="Wedding">Garden Wedding</option>
                        <option value="Bridal/Baby Shower">Bridal/Baby Shower</option>
                        <option value="Office Retreat">Office Retreat</option>
                      </select>
                    </div>
                  </div>
                  
                  
                  <div class="col-sm-12 col-md-12 col-lg-12">
                    <button type="submit" class="btn btn__secondary btn__block" id="btn-submit">Submit Reservation</button>
                    <button class="btn btn__secondary btn__block" type="button" id="loader" style="cursor: not-allowed;">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true" disabled></span>
                    Submitting...
                    </button>
                  </div>
                </div>
              </form>

              <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
              <script type="text/javascript">
              $(document).ready(function () 
                {
                    $("#loader").hide();
                    $("#resform").submit(function (e) {
              
                        $("#btn-submit").hide();
                        $("#loader").show();
              
                        return true;
                
                    });
                });  
              </script>

            
            </div>
          </div>
        </div>
      </div>
    </section>


<!-- Include Footer -->
<?php include_once( "footer.php"); ?>